/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenModuleHelpers.pl
// Created: 2015.01.18 19:26:41

#include "BasicIOSAssetParam_0p0.h"
#include "BasicIOSAssetParam_0p1.h"
#include "BasicIOSAssetParam_0p2.h"
#include "BasicIOSAssetParam_0p3.h"
#include "BasicIOSAssetParam_0p4.h"
#include "BasicIOSAssetParam_0p5.h"
#include "BasicIOSAssetParam_0p6.h"
#include "BasicIOSAssetParam_0p7.h"
#include "BasicIOSAssetParam_0p8.h"
#include "BasicIOSAssetParam_0p9.h"
#include "BasicIOSAssetParam_1p0.h"
#include "BasicIOSAssetParam_1p1.h"
#include "BasicIOSAssetParam_1p2.h"
#include "BasicIOSAssetParam_1p3.h"
#include "BasicIOSAssetParam_1p4.h"
