/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenModuleHelpers.pl
// Created: 2015.01.18 19:26:41

#include "AttractorFSActorParams.h"
#include "AttractorFSAssetParams.h"
#include "AttractorFSPreviewParams.h"
#include "BasicFSDebugRenderParams.h"
#include "BasicFSModuleParameters.h"
#include "JetFSActorParams.h"
#include "JetFSAssetParams.h"
#include "JetFSPreviewParams.h"
#include "NoiseFSActorParams.h"
#include "NoiseFSAssetParams.h"
#include "NoiseFSPreviewParams.h"
#include "VortexFSActorParams.h"
#include "VortexFSAssetParams.h"
#include "VortexFSPreviewParams.h"
#include "WindFSActorParams.h"
#include "WindFSAssetParams.h"
#include "WindFSPreviewParams.h"
