/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenParameterized.pl
// Created: 2015.01.18 19:26:14

#ifndef HEADER_JetFSPreviewParams_h
#define HEADER_JetFSPreviewParams_h

#include "NxParametersTypes.h"

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
#include "NxParameterized.h"
#include "NxParameters.h"
#include "NxParameterizedTraits.h"
#include "NxTraitsInternal.h"
#endif

namespace physx
{
namespace apex
{
namespace basicfs
{

#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())

namespace JetFSPreviewParamsNS
{



struct ParametersStruct
{

	physx::PxMat44 globalPose;
	bool drawShape;
	bool drawAssetInfo;
	physx::PxU64 userData;

};

static const physx::PxU32 checksum[] = { 0xd4ae1ca1, 0x104c2a39, 0xc7e092cd, 0xc962045f, };

} // namespace JetFSPreviewParamsNS

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
class JetFSPreviewParams : public NxParameterized::NxParameters, public JetFSPreviewParamsNS::ParametersStruct
{
public:
	JetFSPreviewParams(NxParameterized::Traits* traits, void* buf = 0, PxI32* refCount = 0);

	virtual ~JetFSPreviewParams();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("JetFSPreviewParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const physx::PxU32 ClassVersion = ((physx::PxU32)0 << 16) + (physx::PxU32)0;

	static physx::PxU32 staticVersion(void)
	{
		return ClassVersion;
	}

	physx::PxU32 version(void) const
	{
		return(staticVersion());
	}

	static const physx::PxU32 ClassAlignment = 8;

	static const physx::PxU32* staticChecksum(physx::PxU32& bits)
	{
		bits = 8 * sizeof(JetFSPreviewParamsNS::checksum);
		return JetFSPreviewParamsNS::checksum;
	}

	static void freeParameterDefinitionTable(NxParameterized::Traits* traits);

	const physx::PxU32* checksum(physx::PxU32& bits) const
	{
		return staticChecksum(bits);
	}

	const JetFSPreviewParamsNS::ParametersStruct& parameters(void) const
	{
		JetFSPreviewParams* tmpThis = const_cast<JetFSPreviewParams*>(this);
		return *(static_cast<JetFSPreviewParamsNS::ParametersStruct*>(tmpThis));
	}

	JetFSPreviewParamsNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<JetFSPreviewParamsNS::ParametersStruct*>(this));
	}

	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle) const;
	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NxParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NxParameterized::MutexType mBuiltFlagMutex;
};

class JetFSPreviewParamsFactory : public NxParameterized::Factory
{
	static const char* const vptr;

public:
	virtual NxParameterized::Interface* create(NxParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(JetFSPreviewParams), JetFSPreviewParams::ClassAlignment);
		if (!NxParameterized::IsAligned(newPtr, JetFSPreviewParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class JetFSPreviewParams");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(JetFSPreviewParams)); // always initialize memory allocated to zero for default values
		return NX_PARAM_PLACEMENT_NEW(newPtr, JetFSPreviewParams)(paramTraits);
	}

	virtual NxParameterized::Interface* finish(NxParameterized::Traits* paramTraits, void* bufObj, void* bufStart, physx::PxI32* refCount)
	{
		if (!NxParameterized::IsAligned(bufObj, JetFSPreviewParams::ClassAlignment)
		        || !NxParameterized::IsAligned(bufStart, JetFSPreviewParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class JetFSPreviewParams");
			return 0;
		}

		// Init NxParameters-part
		// We used to call empty constructor of JetFSPreviewParams here
		// but it may call default constructors of members and spoil the data
		NX_PARAM_PLACEMENT_NEW(bufObj, NxParameterized::NxParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (JetFSPreviewParams*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (JetFSPreviewParams::staticClassName());
	}

	virtual physx::PxU32 getVersion()
	{
		return (JetFSPreviewParams::staticVersion());
	}

	virtual physx::PxU32 getAlignment()
	{
		return (JetFSPreviewParams::ClassAlignment);
	}

	virtual const physx::PxU32* getChecksum(physx::PxU32& bits)
	{
		return (JetFSPreviewParams::staticChecksum(bits));
	}
};
#endif // NX_PARAMETERIZED_ONLY_LAYOUTS

} // namespace basicfs
} // namespace apex
} // namespace physx

#pragma warning(pop)

#endif
