/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenParameterized.pl
// Created: 2015.01.18 19:26:28

#ifndef HEADER_EffectPackageAssetParams_0p0_h
#define HEADER_EffectPackageAssetParams_0p0_h

#include "NxParametersTypes.h"

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
#include "NxParameterized.h"
#include "NxParameters.h"
#include "NxParameterizedTraits.h"
#include "NxTraitsInternal.h"
#endif

namespace physx
{
namespace apex
{

#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())

namespace EffectPackageAssetParams_0p0NS
{

struct ControlPoint_Type;
struct EffectPath_Type;
struct LevelOfDetailSettings_Type;

struct TRANSFORM_DynamicArray1D_Type
{
	physx::PxTransform* buf;
	bool isAllocated;
	physx::PxI32 elementSize;
	physx::PxI32 arraySizes[1];
};

struct ControlPoint_DynamicArray1D_Type
{
	ControlPoint_Type* buf;
	bool isAllocated;
	physx::PxI32 elementSize;
	physx::PxI32 arraySizes[1];
};

struct REF_DynamicArray1D_Type
{
	NxParameterized::Interface** buf;
	bool isAllocated;
	physx::PxI32 elementSize;
	physx::PxI32 arraySizes[1];
};

struct LevelOfDetailSettings_Type
{
	bool UniqueRenderVolume;
	physx::PxF32 FadeDistanceBegin;
	physx::PxF32 FadeDistanceEnd;
	bool RandomizeEmitterRate;
	physx::PxF32 FadeOutRate;
	bool CullByDistance;
	bool CullOffScreen;
	physx::PxF32 OffScreenCullTime;
	physx::PxF32 NonVisibleDeleteTime;
	physx::PxF32 ScreenCullSize;
	physx::PxF32 ScreenCullDistance;
	bool FadeEmitterRate;
	bool FadeAttractorFieldStrength;
	bool FadeJetFieldStrength;
	bool FadeTurbulenceVelocity;
	bool FadeTurbulenceNoise;
	bool FadeTurbulenceExternalVelocity;
	bool FadeTurbulenceVelocityWeight;
	bool FadeHeatSourceTemperature;
	bool FadeForceFieldStrength;
	bool FadeForceFieldScale;
};
struct ControlPoint_Type
{
	physx::PxF32 x;
	physx::PxF32 y;
};
struct EffectPath_Type
{
	const char* PlaybackMode;
	physx::PxF32 PathDuration;
	physx::PxU32 LoopIndex;
	TRANSFORM_DynamicArray1D_Type ControlPoints;
	ControlPoint_DynamicArray1D_Type Scale;
	ControlPoint_DynamicArray1D_Type Speed;
};

struct ParametersStruct
{

	LevelOfDetailSettings_Type LODSettings;
	EffectPath_Type Path;
	REF_DynamicArray1D_Type Effects;

};

static const physx::PxU32 checksum[] = { 0x320fe537, 0x995086b2, 0xdf05d741, 0x2afa43ec, };

} // namespace EffectPackageAssetParams_0p0NS

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
class EffectPackageAssetParams_0p0 : public NxParameterized::NxParameters, public EffectPackageAssetParams_0p0NS::ParametersStruct
{
public:
	EffectPackageAssetParams_0p0(NxParameterized::Traits* traits, void* buf = 0, PxI32* refCount = 0);

	virtual ~EffectPackageAssetParams_0p0();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("EffectPackageAssetParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const physx::PxU32 ClassVersion = ((physx::PxU32)0 << 16) + (physx::PxU32)0;

	static physx::PxU32 staticVersion(void)
	{
		return ClassVersion;
	}

	physx::PxU32 version(void) const
	{
		return(staticVersion());
	}

	static const physx::PxU32 ClassAlignment = 8;

	static const physx::PxU32* staticChecksum(physx::PxU32& bits)
	{
		bits = 8 * sizeof(EffectPackageAssetParams_0p0NS::checksum);
		return EffectPackageAssetParams_0p0NS::checksum;
	}

	static void freeParameterDefinitionTable(NxParameterized::Traits* traits);

	const physx::PxU32* checksum(physx::PxU32& bits) const
	{
		return staticChecksum(bits);
	}

	const EffectPackageAssetParams_0p0NS::ParametersStruct& parameters(void) const
	{
		EffectPackageAssetParams_0p0* tmpThis = const_cast<EffectPackageAssetParams_0p0*>(this);
		return *(static_cast<EffectPackageAssetParams_0p0NS::ParametersStruct*>(tmpThis));
	}

	EffectPackageAssetParams_0p0NS::ParametersStruct& parameters(void)
	{
		return *(static_cast<EffectPackageAssetParams_0p0NS::ParametersStruct*>(this));
	}

	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle) const;
	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NxParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NxParameterized::MutexType mBuiltFlagMutex;
};

class EffectPackageAssetParams_0p0Factory : public NxParameterized::Factory
{
	static const char* const vptr;

public:
	virtual NxParameterized::Interface* create(NxParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(EffectPackageAssetParams_0p0), EffectPackageAssetParams_0p0::ClassAlignment);
		if (!NxParameterized::IsAligned(newPtr, EffectPackageAssetParams_0p0::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class EffectPackageAssetParams_0p0");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(EffectPackageAssetParams_0p0)); // always initialize memory allocated to zero for default values
		return NX_PARAM_PLACEMENT_NEW(newPtr, EffectPackageAssetParams_0p0)(paramTraits);
	}

	virtual NxParameterized::Interface* finish(NxParameterized::Traits* paramTraits, void* bufObj, void* bufStart, physx::PxI32* refCount)
	{
		if (!NxParameterized::IsAligned(bufObj, EffectPackageAssetParams_0p0::ClassAlignment)
		        || !NxParameterized::IsAligned(bufStart, EffectPackageAssetParams_0p0::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class EffectPackageAssetParams_0p0");
			return 0;
		}

		// Init NxParameters-part
		// We used to call empty constructor of EffectPackageAssetParams_0p0 here
		// but it may call default constructors of members and spoil the data
		NX_PARAM_PLACEMENT_NEW(bufObj, NxParameterized::NxParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (EffectPackageAssetParams_0p0*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (EffectPackageAssetParams_0p0::staticClassName());
	}

	virtual physx::PxU32 getVersion()
	{
		return (EffectPackageAssetParams_0p0::staticVersion());
	}

	virtual physx::PxU32 getAlignment()
	{
		return (EffectPackageAssetParams_0p0::ClassAlignment);
	}

	virtual const physx::PxU32* getChecksum(physx::PxU32& bits)
	{
		return (EffectPackageAssetParams_0p0::staticChecksum(bits));
	}
};
#endif // NX_PARAMETERIZED_ONLY_LAYOUTS

} // namespace apex
} // namespace physx

#pragma warning(pop)

#endif
