/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenModuleHelpers.pl
// Created: 2015.01.18 19:26:41

#include "AttractorFSAssetParams_0p0.h"
#include "AttractorFSAssetParams_0p1.h"
#include "JetFSAssetParams_0p0.h"
#include "JetFSAssetParams_0p1.h"
#include "NoiseFSAssetParams_0p0.h"
#include "NoiseFSAssetParams_0p1.h"
#include "NoiseFSAssetParams_0p2.h"
#include "VortexFSAssetParams_0p0.h"
#include "VortexFSAssetParams_0p1.h"
#include "VortexFSAssetParams_0p2.h"
#include "WindFSAssetParams_0p0.h"
#include "WindFSAssetParams_0p1.h"
