/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenParameterized.pl
// Created: 2015.01.18 19:26:25

#ifndef HEADER_FlameEmitterData_h
#define HEADER_FlameEmitterData_h

#include "NxParametersTypes.h"

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
#include "NxParameterized.h"
#include "NxParameters.h"
#include "NxParameterizedTraits.h"
#include "NxTraitsInternal.h"
#endif

namespace physx
{
namespace apex
{
namespace particles
{

#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())

namespace FlameEmitterDataNS
{



struct ParametersStruct
{

	NxParameterized::DummyStringStruct Name;
	NxParameterized::Interface* FlameEmitter;

};

static const physx::PxU32 checksum[] = { 0x90a03422, 0x50c8e759, 0xf9df589f, 0x56836e65, };

} // namespace FlameEmitterDataNS

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
class FlameEmitterData : public NxParameterized::NxParameters, public FlameEmitterDataNS::ParametersStruct
{
public:
	FlameEmitterData(NxParameterized::Traits* traits, void* buf = 0, PxI32* refCount = 0);

	virtual ~FlameEmitterData();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("FlameEmitterData");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const physx::PxU32 ClassVersion = ((physx::PxU32)0 << 16) + (physx::PxU32)0;

	static physx::PxU32 staticVersion(void)
	{
		return ClassVersion;
	}

	physx::PxU32 version(void) const
	{
		return(staticVersion());
	}

	static const physx::PxU32 ClassAlignment = 8;

	static const physx::PxU32* staticChecksum(physx::PxU32& bits)
	{
		bits = 8 * sizeof(FlameEmitterDataNS::checksum);
		return FlameEmitterDataNS::checksum;
	}

	static void freeParameterDefinitionTable(NxParameterized::Traits* traits);

	const physx::PxU32* checksum(physx::PxU32& bits) const
	{
		return staticChecksum(bits);
	}

	const FlameEmitterDataNS::ParametersStruct& parameters(void) const
	{
		FlameEmitterData* tmpThis = const_cast<FlameEmitterData*>(this);
		return *(static_cast<FlameEmitterDataNS::ParametersStruct*>(tmpThis));
	}

	FlameEmitterDataNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<FlameEmitterDataNS::ParametersStruct*>(this));
	}

	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle) const;
	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NxParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NxParameterized::MutexType mBuiltFlagMutex;
};

class FlameEmitterDataFactory : public NxParameterized::Factory
{
	static const char* const vptr;

public:
	virtual NxParameterized::Interface* create(NxParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(FlameEmitterData), FlameEmitterData::ClassAlignment);
		if (!NxParameterized::IsAligned(newPtr, FlameEmitterData::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class FlameEmitterData");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(FlameEmitterData)); // always initialize memory allocated to zero for default values
		return NX_PARAM_PLACEMENT_NEW(newPtr, FlameEmitterData)(paramTraits);
	}

	virtual NxParameterized::Interface* finish(NxParameterized::Traits* paramTraits, void* bufObj, void* bufStart, physx::PxI32* refCount)
	{
		if (!NxParameterized::IsAligned(bufObj, FlameEmitterData::ClassAlignment)
		        || !NxParameterized::IsAligned(bufStart, FlameEmitterData::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class FlameEmitterData");
			return 0;
		}

		// Init NxParameters-part
		// We used to call empty constructor of FlameEmitterData here
		// but it may call default constructors of members and spoil the data
		NX_PARAM_PLACEMENT_NEW(bufObj, NxParameterized::NxParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (FlameEmitterData*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (FlameEmitterData::staticClassName());
	}

	virtual physx::PxU32 getVersion()
	{
		return (FlameEmitterData::staticVersion());
	}

	virtual physx::PxU32 getAlignment()
	{
		return (FlameEmitterData::ClassAlignment);
	}

	virtual const physx::PxU32* getChecksum(physx::PxU32& bits)
	{
		return (FlameEmitterData::staticChecksum(bits));
	}
};
#endif // NX_PARAMETERIZED_ONLY_LAYOUTS

} // namespace particles
} // namespace apex
} // namespace physx

#pragma warning(pop)

#endif
