/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenParameterized.pl
// Created: 2015.01.18 19:26:26

#ifndef HEADER_FlameEmitterAssetParams_h
#define HEADER_FlameEmitterAssetParams_h

#include "NxParametersTypes.h"

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
#include "NxParameterized.h"
#include "NxParameters.h"
#include "NxParameterizedTraits.h"
#include "NxTraitsInternal.h"
#endif

namespace physx
{
namespace apex
{
namespace turbulencefs
{

#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())

namespace FlameEmitterAssetParamsNS
{



struct ParametersStruct
{

	const char* EmitterType;
	physx::PxF32 Length;
	physx::PxF32 Radius;
	physx::PxF32 EdgeWidth;
	physx::PxVec4 Velocity;
	physx::PxVec4 DensityValue;
	physx::PxVec4 DensityOuterValue;
	physx::PxF32 NoiseStrength;
	physx::PxF32 DistanceNoiseStrength;
	physx::PxVec3 NoiseFrequency;
	physx::PxU32 NoiseOctaves;
	physx::PxF32 NoiseAnimationSpeed;
	NxParameterized::DummyStringStruct fieldSamplerFilterDataName;

};

static const physx::PxU32 checksum[] = { 0xcdaeb280, 0xdaeddca6, 0x8e0886d1, 0x2186ff94, };

} // namespace FlameEmitterAssetParamsNS

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
class FlameEmitterAssetParams : public NxParameterized::NxParameters, public FlameEmitterAssetParamsNS::ParametersStruct
{
public:
	FlameEmitterAssetParams(NxParameterized::Traits* traits, void* buf = 0, PxI32* refCount = 0);

	virtual ~FlameEmitterAssetParams();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("FlameEmitterAssetParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const physx::PxU32 ClassVersion = ((physx::PxU32)0 << 16) + (physx::PxU32)0;

	static physx::PxU32 staticVersion(void)
	{
		return ClassVersion;
	}

	physx::PxU32 version(void) const
	{
		return(staticVersion());
	}

	static const physx::PxU32 ClassAlignment = 8;

	static const physx::PxU32* staticChecksum(physx::PxU32& bits)
	{
		bits = 8 * sizeof(FlameEmitterAssetParamsNS::checksum);
		return FlameEmitterAssetParamsNS::checksum;
	}

	static void freeParameterDefinitionTable(NxParameterized::Traits* traits);

	const physx::PxU32* checksum(physx::PxU32& bits) const
	{
		return staticChecksum(bits);
	}

	const FlameEmitterAssetParamsNS::ParametersStruct& parameters(void) const
	{
		FlameEmitterAssetParams* tmpThis = const_cast<FlameEmitterAssetParams*>(this);
		return *(static_cast<FlameEmitterAssetParamsNS::ParametersStruct*>(tmpThis));
	}

	FlameEmitterAssetParamsNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<FlameEmitterAssetParamsNS::ParametersStruct*>(this));
	}

	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle) const;
	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NxParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NxParameterized::MutexType mBuiltFlagMutex;
};

class FlameEmitterAssetParamsFactory : public NxParameterized::Factory
{
	static const char* const vptr;

public:
	virtual NxParameterized::Interface* create(NxParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(FlameEmitterAssetParams), FlameEmitterAssetParams::ClassAlignment);
		if (!NxParameterized::IsAligned(newPtr, FlameEmitterAssetParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class FlameEmitterAssetParams");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(FlameEmitterAssetParams)); // always initialize memory allocated to zero for default values
		return NX_PARAM_PLACEMENT_NEW(newPtr, FlameEmitterAssetParams)(paramTraits);
	}

	virtual NxParameterized::Interface* finish(NxParameterized::Traits* paramTraits, void* bufObj, void* bufStart, physx::PxI32* refCount)
	{
		if (!NxParameterized::IsAligned(bufObj, FlameEmitterAssetParams::ClassAlignment)
		        || !NxParameterized::IsAligned(bufStart, FlameEmitterAssetParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class FlameEmitterAssetParams");
			return 0;
		}

		// Init NxParameters-part
		// We used to call empty constructor of FlameEmitterAssetParams here
		// but it may call default constructors of members and spoil the data
		NX_PARAM_PLACEMENT_NEW(bufObj, NxParameterized::NxParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (FlameEmitterAssetParams*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (FlameEmitterAssetParams::staticClassName());
	}

	virtual physx::PxU32 getVersion()
	{
		return (FlameEmitterAssetParams::staticVersion());
	}

	virtual physx::PxU32 getAlignment()
	{
		return (FlameEmitterAssetParams::ClassAlignment);
	}

	virtual const physx::PxU32* getChecksum(physx::PxU32& bits)
	{
		return (FlameEmitterAssetParams::staticChecksum(bits));
	}
};
#endif // NX_PARAMETERIZED_ONLY_LAYOUTS

} // namespace turbulencefs
} // namespace apex
} // namespace physx

#pragma warning(pop)

#endif
