/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenModuleHelpers.pl
// Created: 2015.01.18 19:26:43

#include "FlameEmitterActorParams.h"
#include "FlameEmitterAssetParams.h"
#include "FlameEmitterPreviewParams.h"
#include "HeatSourceActorParams.h"
#include "HeatSourceAssetParams.h"
#include "HeatSourceGeomBoxParams.h"
#include "HeatSourceGeomSphereParams.h"
#include "HeatSourcePreviewParams.h"
#include "SubstanceSourceActorParams.h"
#include "SubstanceSourceAssetParams.h"
#include "TurbulenceFSActorParams.h"
#include "TurbulenceFSAssetParams.h"
#include "TurbulenceFSDebugRenderParams.h"
#include "TurbulenceFSModuleParameters.h"
#include "TurbulenceFSPreviewParams.h"
#include "VelocitySourceActorParams.h"
#include "VelocitySourceAssetParams.h"
#include "VelocitySourcePreviewParams.h"
