/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenParameterized.pl
// Created: 2015.01.18 19:26:26

#ifndef HEADER_ParticleIosDebugRenderParams_h
#define HEADER_ParticleIosDebugRenderParams_h

#include "NxParametersTypes.h"

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
#include "NxParameterized.h"
#include "NxParameters.h"
#include "NxParameterizedTraits.h"
#include "NxTraitsInternal.h"
#endif

namespace physx
{
namespace apex
{
namespace pxparticleios
{

#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())

namespace ParticleIosDebugRenderParamsNS
{



struct ParametersStruct
{

	bool VISUALIZE_PARTICLE_IOS_ACTOR;
	bool VISUALIZE_PARTICLE_IOS_GRID_DENSITY;

};

static const physx::PxU32 checksum[] = { 0x271c2489, 0x3bbc0436, 0x9f681969, 0x1c05e617, };

} // namespace ParticleIosDebugRenderParamsNS

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
class ParticleIosDebugRenderParams : public NxParameterized::NxParameters, public ParticleIosDebugRenderParamsNS::ParametersStruct
{
public:
	ParticleIosDebugRenderParams(NxParameterized::Traits* traits, void* buf = 0, PxI32* refCount = 0);

	virtual ~ParticleIosDebugRenderParams();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("ParticleIosDebugRenderParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const physx::PxU32 ClassVersion = ((physx::PxU32)0 << 16) + (physx::PxU32)0;

	static physx::PxU32 staticVersion(void)
	{
		return ClassVersion;
	}

	physx::PxU32 version(void) const
	{
		return(staticVersion());
	}

	static const physx::PxU32 ClassAlignment = 8;

	static const physx::PxU32* staticChecksum(physx::PxU32& bits)
	{
		bits = 8 * sizeof(ParticleIosDebugRenderParamsNS::checksum);
		return ParticleIosDebugRenderParamsNS::checksum;
	}

	static void freeParameterDefinitionTable(NxParameterized::Traits* traits);

	const physx::PxU32* checksum(physx::PxU32& bits) const
	{
		return staticChecksum(bits);
	}

	const ParticleIosDebugRenderParamsNS::ParametersStruct& parameters(void) const
	{
		ParticleIosDebugRenderParams* tmpThis = const_cast<ParticleIosDebugRenderParams*>(this);
		return *(static_cast<ParticleIosDebugRenderParamsNS::ParametersStruct*>(tmpThis));
	}

	ParticleIosDebugRenderParamsNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<ParticleIosDebugRenderParamsNS::ParametersStruct*>(this));
	}

	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle) const;
	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NxParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NxParameterized::MutexType mBuiltFlagMutex;
};

class ParticleIosDebugRenderParamsFactory : public NxParameterized::Factory
{
	static const char* const vptr;

public:
	virtual NxParameterized::Interface* create(NxParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(ParticleIosDebugRenderParams), ParticleIosDebugRenderParams::ClassAlignment);
		if (!NxParameterized::IsAligned(newPtr, ParticleIosDebugRenderParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class ParticleIosDebugRenderParams");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(ParticleIosDebugRenderParams)); // always initialize memory allocated to zero for default values
		return NX_PARAM_PLACEMENT_NEW(newPtr, ParticleIosDebugRenderParams)(paramTraits);
	}

	virtual NxParameterized::Interface* finish(NxParameterized::Traits* paramTraits, void* bufObj, void* bufStart, physx::PxI32* refCount)
	{
		if (!NxParameterized::IsAligned(bufObj, ParticleIosDebugRenderParams::ClassAlignment)
		        || !NxParameterized::IsAligned(bufStart, ParticleIosDebugRenderParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class ParticleIosDebugRenderParams");
			return 0;
		}

		// Init NxParameters-part
		// We used to call empty constructor of ParticleIosDebugRenderParams here
		// but it may call default constructors of members and spoil the data
		NX_PARAM_PLACEMENT_NEW(bufObj, NxParameterized::NxParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (ParticleIosDebugRenderParams*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (ParticleIosDebugRenderParams::staticClassName());
	}

	virtual physx::PxU32 getVersion()
	{
		return (ParticleIosDebugRenderParams::staticVersion());
	}

	virtual physx::PxU32 getAlignment()
	{
		return (ParticleIosDebugRenderParams::ClassAlignment);
	}

	virtual const physx::PxU32* getChecksum(physx::PxU32& bits)
	{
		return (ParticleIosDebugRenderParams::staticChecksum(bits));
	}
};
#endif // NX_PARAMETERIZED_ONLY_LAYOUTS

} // namespace pxparticleios
} // namespace apex
} // namespace physx

#pragma warning(pop)

#endif
