/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenParameterized.pl
// Created: 2015.01.18 19:26:24

#ifndef HEADER_ColorVsTemperatureCompositeModifierParams_h
#define HEADER_ColorVsTemperatureCompositeModifierParams_h

#include "NxParametersTypes.h"

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
#include "NxParameterized.h"
#include "NxParameters.h"
#include "NxParameterizedTraits.h"
#include "NxTraitsInternal.h"
#endif

namespace physx
{
namespace apex
{
namespace iofx
{

#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())

namespace ColorVsTemperatureCompositeModifierParamsNS
{

struct colorTemperatureStruct_Type;

struct colorTemperatureStruct_DynamicArray1D_Type
{
	colorTemperatureStruct_Type* buf;
	bool isAllocated;
	physx::PxI32 elementSize;
	physx::PxI32 arraySizes[1];
};

struct colorTemperatureStruct_Type
{
	physx::PxF32 temperature;
	physx::PxVec4 color;
};

struct ParametersStruct
{

	colorTemperatureStruct_DynamicArray1D_Type controlPoints;

};

static const physx::PxU32 checksum[] = { 0xb5bad295, 0x1bbde1e7, 0xb10b2dc3, 0xde67581e, };

} // namespace ColorVsTemperatureCompositeModifierParamsNS

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
class ColorVsTemperatureCompositeModifierParams : public NxParameterized::NxParameters, public ColorVsTemperatureCompositeModifierParamsNS::ParametersStruct
{
public:
	ColorVsTemperatureCompositeModifierParams(NxParameterized::Traits* traits, void* buf = 0, PxI32* refCount = 0);

	virtual ~ColorVsTemperatureCompositeModifierParams();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("ColorVsTemperatureCompositeModifierParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const physx::PxU32 ClassVersion = ((physx::PxU32)0 << 16) + (physx::PxU32)0;

	static physx::PxU32 staticVersion(void)
	{
		return ClassVersion;
	}

	physx::PxU32 version(void) const
	{
		return(staticVersion());
	}

	static const physx::PxU32 ClassAlignment = 8;

	static const physx::PxU32* staticChecksum(physx::PxU32& bits)
	{
		bits = 8 * sizeof(ColorVsTemperatureCompositeModifierParamsNS::checksum);
		return ColorVsTemperatureCompositeModifierParamsNS::checksum;
	}

	static void freeParameterDefinitionTable(NxParameterized::Traits* traits);

	const physx::PxU32* checksum(physx::PxU32& bits) const
	{
		return staticChecksum(bits);
	}

	const ColorVsTemperatureCompositeModifierParamsNS::ParametersStruct& parameters(void) const
	{
		ColorVsTemperatureCompositeModifierParams* tmpThis = const_cast<ColorVsTemperatureCompositeModifierParams*>(this);
		return *(static_cast<ColorVsTemperatureCompositeModifierParamsNS::ParametersStruct*>(tmpThis));
	}

	ColorVsTemperatureCompositeModifierParamsNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<ColorVsTemperatureCompositeModifierParamsNS::ParametersStruct*>(this));
	}

	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle) const;
	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NxParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NxParameterized::MutexType mBuiltFlagMutex;
};

class ColorVsTemperatureCompositeModifierParamsFactory : public NxParameterized::Factory
{
	static const char* const vptr;

public:
	virtual NxParameterized::Interface* create(NxParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(ColorVsTemperatureCompositeModifierParams), ColorVsTemperatureCompositeModifierParams::ClassAlignment);
		if (!NxParameterized::IsAligned(newPtr, ColorVsTemperatureCompositeModifierParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class ColorVsTemperatureCompositeModifierParams");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(ColorVsTemperatureCompositeModifierParams)); // always initialize memory allocated to zero for default values
		return NX_PARAM_PLACEMENT_NEW(newPtr, ColorVsTemperatureCompositeModifierParams)(paramTraits);
	}

	virtual NxParameterized::Interface* finish(NxParameterized::Traits* paramTraits, void* bufObj, void* bufStart, physx::PxI32* refCount)
	{
		if (!NxParameterized::IsAligned(bufObj, ColorVsTemperatureCompositeModifierParams::ClassAlignment)
		        || !NxParameterized::IsAligned(bufStart, ColorVsTemperatureCompositeModifierParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class ColorVsTemperatureCompositeModifierParams");
			return 0;
		}

		// Init NxParameters-part
		// We used to call empty constructor of ColorVsTemperatureCompositeModifierParams here
		// but it may call default constructors of members and spoil the data
		NX_PARAM_PLACEMENT_NEW(bufObj, NxParameterized::NxParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (ColorVsTemperatureCompositeModifierParams*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (ColorVsTemperatureCompositeModifierParams::staticClassName());
	}

	virtual physx::PxU32 getVersion()
	{
		return (ColorVsTemperatureCompositeModifierParams::staticVersion());
	}

	virtual physx::PxU32 getAlignment()
	{
		return (ColorVsTemperatureCompositeModifierParams::ClassAlignment);
	}

	virtual const physx::PxU32* getChecksum(physx::PxU32& bits)
	{
		return (ColorVsTemperatureCompositeModifierParams::staticChecksum(bits));
	}
};
#endif // NX_PARAMETERIZED_ONLY_LAYOUTS

} // namespace iofx
} // namespace apex
} // namespace physx

#pragma warning(pop)

#endif
