/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenModuleHelpers.pl
// Created: 2015.01.18 19:26:43

#include "ColorVsDensityCompositeModifierParams.h"
#include "ColorVsDensityModifierParams.h"
#include "ColorVsLifeCompositeModifierParams.h"
#include "ColorVsLifeModifierParams.h"
#include "ColorVsTemperatureCompositeModifierParams.h"
#include "ColorVsTemperatureModifierParams.h"
#include "ColorVsVelocityCompositeModifierParams.h"
#include "ColorVsVelocityModifierParams.h"
#include "InitialColorModifierParams.h"
#include "IofxAssetParameters.h"
#include "IofxDebugRenderParams.h"
#include "IofxModuleParameters.h"
#include "MeshIofxParameters.h"
#include "OrientAlongVelocityModifierParams.h"
#include "OrientScaleAlongScreenVelocityModifierParams.h"
#include "RandomRotationModifierParams.h"
#include "RandomScaleModifierParams.h"
#include "RandomSubtextureModifierParams.h"
#include "RotationModifierParams.h"
#include "RotationRateModifierParams.h"
#include "RotationRateVsLifeModifierParams.h"
#include "ScaleAlongVelocityModifierParams.h"
#include "ScaleByMassModifierParams.h"
#include "ScaleVsCameraDistance2DModifierParams.h"
#include "ScaleVsCameraDistance3DModifierParams.h"
#include "ScaleVsCameraDistanceModifierParams.h"
#include "ScaleVsDensity2DModifierParams.h"
#include "ScaleVsDensity3DModifierParams.h"
#include "ScaleVsDensityModifierParams.h"
#include "ScaleVsLife2DModifierParams.h"
#include "ScaleVsLife3DModifierParams.h"
#include "ScaleVsLifeModifierParams.h"
#include "ScaleVsTemperature2DModifierParams.h"
#include "ScaleVsTemperature3DModifierParams.h"
#include "ScaleVsTemperatureModifierParams.h"
#include "SimpleScaleModifierParams.h"
#include "SpriteIofxParameters.h"
#include "SubtextureVsLifeModifierParams.h"
#include "ViewDirectionSortingModifierParams.h"
