/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenParameterized.pl
// Created: 2015.01.18 19:26:24

#ifndef HEADER_ScaleVsTemperature2DModifierParams_h
#define HEADER_ScaleVsTemperature2DModifierParams_h

#include "NxParametersTypes.h"

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
#include "NxParameterized.h"
#include "NxParameters.h"
#include "NxParameterizedTraits.h"
#include "NxTraitsInternal.h"
#endif

namespace physx
{
namespace apex
{
namespace iofx
{

#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())

namespace ScaleVsTemperature2DModifierParamsNS
{

struct scaleTemperatureStruct_Type;

struct scaleTemperatureStruct_DynamicArray1D_Type
{
	scaleTemperatureStruct_Type* buf;
	bool isAllocated;
	physx::PxI32 elementSize;
	physx::PxI32 arraySizes[1];
};

struct scaleTemperatureStruct_Type
{
	physx::PxF32 temperature;
	physx::PxVec2 scale;
};

struct ParametersStruct
{

	scaleTemperatureStruct_DynamicArray1D_Type controlPoints;

};

static const physx::PxU32 checksum[] = { 0xd5330296, 0xc6fa1947, 0x152d1b30, 0x07453e5c, };

} // namespace ScaleVsTemperature2DModifierParamsNS

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
class ScaleVsTemperature2DModifierParams : public NxParameterized::NxParameters, public ScaleVsTemperature2DModifierParamsNS::ParametersStruct
{
public:
	ScaleVsTemperature2DModifierParams(NxParameterized::Traits* traits, void* buf = 0, PxI32* refCount = 0);

	virtual ~ScaleVsTemperature2DModifierParams();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("ScaleVsTemperature2DModifierParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const physx::PxU32 ClassVersion = ((physx::PxU32)0 << 16) + (physx::PxU32)0;

	static physx::PxU32 staticVersion(void)
	{
		return ClassVersion;
	}

	physx::PxU32 version(void) const
	{
		return(staticVersion());
	}

	static const physx::PxU32 ClassAlignment = 8;

	static const physx::PxU32* staticChecksum(physx::PxU32& bits)
	{
		bits = 8 * sizeof(ScaleVsTemperature2DModifierParamsNS::checksum);
		return ScaleVsTemperature2DModifierParamsNS::checksum;
	}

	static void freeParameterDefinitionTable(NxParameterized::Traits* traits);

	const physx::PxU32* checksum(physx::PxU32& bits) const
	{
		return staticChecksum(bits);
	}

	const ScaleVsTemperature2DModifierParamsNS::ParametersStruct& parameters(void) const
	{
		ScaleVsTemperature2DModifierParams* tmpThis = const_cast<ScaleVsTemperature2DModifierParams*>(this);
		return *(static_cast<ScaleVsTemperature2DModifierParamsNS::ParametersStruct*>(tmpThis));
	}

	ScaleVsTemperature2DModifierParamsNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<ScaleVsTemperature2DModifierParamsNS::ParametersStruct*>(this));
	}

	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle) const;
	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NxParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NxParameterized::MutexType mBuiltFlagMutex;
};

class ScaleVsTemperature2DModifierParamsFactory : public NxParameterized::Factory
{
	static const char* const vptr;

public:
	virtual NxParameterized::Interface* create(NxParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(ScaleVsTemperature2DModifierParams), ScaleVsTemperature2DModifierParams::ClassAlignment);
		if (!NxParameterized::IsAligned(newPtr, ScaleVsTemperature2DModifierParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class ScaleVsTemperature2DModifierParams");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(ScaleVsTemperature2DModifierParams)); // always initialize memory allocated to zero for default values
		return NX_PARAM_PLACEMENT_NEW(newPtr, ScaleVsTemperature2DModifierParams)(paramTraits);
	}

	virtual NxParameterized::Interface* finish(NxParameterized::Traits* paramTraits, void* bufObj, void* bufStart, physx::PxI32* refCount)
	{
		if (!NxParameterized::IsAligned(bufObj, ScaleVsTemperature2DModifierParams::ClassAlignment)
		        || !NxParameterized::IsAligned(bufStart, ScaleVsTemperature2DModifierParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class ScaleVsTemperature2DModifierParams");
			return 0;
		}

		// Init NxParameters-part
		// We used to call empty constructor of ScaleVsTemperature2DModifierParams here
		// but it may call default constructors of members and spoil the data
		NX_PARAM_PLACEMENT_NEW(bufObj, NxParameterized::NxParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (ScaleVsTemperature2DModifierParams*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (ScaleVsTemperature2DModifierParams::staticClassName());
	}

	virtual physx::PxU32 getVersion()
	{
		return (ScaleVsTemperature2DModifierParams::staticVersion());
	}

	virtual physx::PxU32 getAlignment()
	{
		return (ScaleVsTemperature2DModifierParams::ClassAlignment);
	}

	virtual const physx::PxU32* getChecksum(physx::PxU32& bits)
	{
		return (ScaleVsTemperature2DModifierParams::staticChecksum(bits));
	}
};
#endif // NX_PARAMETERIZED_ONLY_LAYOUTS

} // namespace iofx
} // namespace apex
} // namespace physx

#pragma warning(pop)

#endif
