/*
 * Copyright (c) 2008-2015, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */


// This file was generated by NxParameterized/scripts/GenParameterized.pl
// Created: 2015.01.18 19:26:24

#ifndef HEADER_ScaleVsDensity3DModifierParams_h
#define HEADER_ScaleVsDensity3DModifierParams_h

#include "NxParametersTypes.h"

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
#include "NxParameterized.h"
#include "NxParameters.h"
#include "NxParameterizedTraits.h"
#include "NxTraitsInternal.h"
#endif

namespace physx
{
namespace apex
{
namespace iofx
{

#pragma warning(push)
#pragma warning(disable: 4324) // structure was padded due to __declspec(align())

namespace ScaleVsDensity3DModifierParamsNS
{

struct scaleDensityStruct_Type;

struct scaleDensityStruct_DynamicArray1D_Type
{
	scaleDensityStruct_Type* buf;
	bool isAllocated;
	physx::PxI32 elementSize;
	physx::PxI32 arraySizes[1];
};

struct scaleDensityStruct_Type
{
	physx::PxF32 density;
	physx::PxVec3 scale;
};

struct ParametersStruct
{

	scaleDensityStruct_DynamicArray1D_Type controlPoints;

};

static const physx::PxU32 checksum[] = { 0x0dddf0d6, 0x459996e0, 0x32b4d7ce, 0x8e0d1b52, };

} // namespace ScaleVsDensity3DModifierParamsNS

#ifndef NX_PARAMETERIZED_ONLY_LAYOUTS
class ScaleVsDensity3DModifierParams : public NxParameterized::NxParameters, public ScaleVsDensity3DModifierParamsNS::ParametersStruct
{
public:
	ScaleVsDensity3DModifierParams(NxParameterized::Traits* traits, void* buf = 0, PxI32* refCount = 0);

	virtual ~ScaleVsDensity3DModifierParams();

	virtual void destroy();

	static const char* staticClassName(void)
	{
		return("ScaleVsDensity3DModifierParams");
	}

	const char* className(void) const
	{
		return(staticClassName());
	}

	static const physx::PxU32 ClassVersion = ((physx::PxU32)0 << 16) + (physx::PxU32)0;

	static physx::PxU32 staticVersion(void)
	{
		return ClassVersion;
	}

	physx::PxU32 version(void) const
	{
		return(staticVersion());
	}

	static const physx::PxU32 ClassAlignment = 8;

	static const physx::PxU32* staticChecksum(physx::PxU32& bits)
	{
		bits = 8 * sizeof(ScaleVsDensity3DModifierParamsNS::checksum);
		return ScaleVsDensity3DModifierParamsNS::checksum;
	}

	static void freeParameterDefinitionTable(NxParameterized::Traits* traits);

	const physx::PxU32* checksum(physx::PxU32& bits) const
	{
		return staticChecksum(bits);
	}

	const ScaleVsDensity3DModifierParamsNS::ParametersStruct& parameters(void) const
	{
		ScaleVsDensity3DModifierParams* tmpThis = const_cast<ScaleVsDensity3DModifierParams*>(this);
		return *(static_cast<ScaleVsDensity3DModifierParamsNS::ParametersStruct*>(tmpThis));
	}

	ScaleVsDensity3DModifierParamsNS::ParametersStruct& parameters(void)
	{
		return *(static_cast<ScaleVsDensity3DModifierParamsNS::ParametersStruct*>(this));
	}

	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle) const;
	virtual NxParameterized::ErrorType getParameterHandle(const char* long_name, NxParameterized::Handle& handle);

	void initDefaults(void);

protected:

	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void);
	virtual const NxParameterized::DefinitionImpl* getParameterDefinitionTree(void) const;


	virtual void getVarPtr(const NxParameterized::Handle& handle, void*& ptr, size_t& offset) const;

private:

	void buildTree(void);
	void initDynamicArrays(void);
	void initStrings(void);
	void initReferences(void);
	void freeDynamicArrays(void);
	void freeStrings(void);
	void freeReferences(void);

	static bool mBuiltFlag;
	static NxParameterized::MutexType mBuiltFlagMutex;
};

class ScaleVsDensity3DModifierParamsFactory : public NxParameterized::Factory
{
	static const char* const vptr;

public:
	virtual NxParameterized::Interface* create(NxParameterized::Traits* paramTraits)
	{
		// placement new on this class using mParameterizedTraits

		void* newPtr = paramTraits->alloc(sizeof(ScaleVsDensity3DModifierParams), ScaleVsDensity3DModifierParams::ClassAlignment);
		if (!NxParameterized::IsAligned(newPtr, ScaleVsDensity3DModifierParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class ScaleVsDensity3DModifierParams");
			paramTraits->free(newPtr);
			return 0;
		}

		memset(newPtr, 0, sizeof(ScaleVsDensity3DModifierParams)); // always initialize memory allocated to zero for default values
		return NX_PARAM_PLACEMENT_NEW(newPtr, ScaleVsDensity3DModifierParams)(paramTraits);
	}

	virtual NxParameterized::Interface* finish(NxParameterized::Traits* paramTraits, void* bufObj, void* bufStart, physx::PxI32* refCount)
	{
		if (!NxParameterized::IsAligned(bufObj, ScaleVsDensity3DModifierParams::ClassAlignment)
		        || !NxParameterized::IsAligned(bufStart, ScaleVsDensity3DModifierParams::ClassAlignment))
		{
			NX_PARAM_TRAITS_WARNING(paramTraits, "Unaligned memory allocation for class ScaleVsDensity3DModifierParams");
			return 0;
		}

		// Init NxParameters-part
		// We used to call empty constructor of ScaleVsDensity3DModifierParams here
		// but it may call default constructors of members and spoil the data
		NX_PARAM_PLACEMENT_NEW(bufObj, NxParameterized::NxParameters)(paramTraits, bufStart, refCount);

		// Init vtable (everything else is already initialized)
		*(const char**)bufObj = vptr;

		return (ScaleVsDensity3DModifierParams*)bufObj;
	}

	virtual const char* getClassName()
	{
		return (ScaleVsDensity3DModifierParams::staticClassName());
	}

	virtual physx::PxU32 getVersion()
	{
		return (ScaleVsDensity3DModifierParams::staticVersion());
	}

	virtual physx::PxU32 getAlignment()
	{
		return (ScaleVsDensity3DModifierParams::ClassAlignment);
	}

	virtual const physx::PxU32* getChecksum(physx::PxU32& bits)
	{
		return (ScaleVsDensity3DModifierParams::staticChecksum(bits));
	}
};
#endif // NX_PARAMETERIZED_ONLY_LAYOUTS

} // namespace iofx
} // namespace apex
} // namespace physx

#pragma warning(pop)

#endif
